# Generated by Django 4.0.2 on 2022-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godina',
            name='godina',
            field=models.DateField(),
        ),
    ]
