# Generated by Django 4.0.2 on 2022-02-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovnici', '0002_alter_godina_godina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanovnik',
            name='godina_rodjenja',
            field=models.DateField(),
        ),
    ]
