# Generated by Django 4.0.2 on 2022-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovnici', '0003_alter_stanovnik_godina_rodjenja'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanovnik',
            name='strani_jezici',
            field=models.ManyToManyField(related_name='strani_jezici', to='stanovnici.StraniJezik'),
        ),
    ]
