# Generated by Django 4.0.2 on 2022-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovnici', '0006_alter_stanovnik_grad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanovnik',
            name='strani_jezici',
            field=models.ManyToManyField(null=True, related_name='strani_jezici', to='stanovnici.StraniJezik'),
        ),
    ]
