# Generated by Django 4.0.2 on 2022-02-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stanovnici', '0007_alter_stanovnik_strani_jezici'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanovnik',
            old_name='bracni_status_id',
            new_name='bracni_status',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='drzavljanstvo_id',
            new_name='drzavljanstvo',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='ekonomska_aktivnost_id',
            new_name='ekonomska_aktivnost',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='godina_id',
            new_name='godina',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='grad_id',
            new_name='grad',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='jezik_id',
            new_name='jezik',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='nacionalnost_id',
            new_name='nacionalnost',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='obrazovanje_id',
            new_name='obrazovanje',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='pismenost_id',
            new_name='pismenost',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='pol_id',
            new_name='pol',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='racunarska_pismenost_id',
            new_name='racunarska_pismenost',
        ),
        migrations.RenameField(
            model_name='stanovnik',
            old_name='vjeroispovijest_id',
            new_name='vjeroispovijest',
        ),
    ]
