# Generated by Django 4.0.2 on 2022-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovnici', '0008_rename_bracni_status_id_stanovnik_bracni_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drzavljanstvno',
            new_name='Drzavljanstvo',
        ),
        migrations.AlterField(
            model_name='stanovnik',
            name='strani_jezici',
            field=models.ManyToManyField(related_name='strani_jezici', to='stanovnici.StraniJezik'),
        ),
    ]
